function out = call_sim(node_csv, edge_csv, seed, base, over)
% 统一调用；把 base 与覆盖项 over 合并
args = base;
fn = fieldnames(over);
for k = 1:numel(fn), args.(fn{k}) = over.(fn{k}); end

out = simulate_dynamic_cascade_final(node_csv, edge_csv, ...
    'Seed',seed, 'MaxSteps',args.MaxSteps, ...
    'FlowModel',args.FlowModel, ...
    'Beta',args.Beta, 'GammaWind',args.GammaWind, 'LenEta',args.LenEta, ...
    'ReduceThreshold',args.ReduceThreshold, 'DemandCut',args.DemandCut, ...
    'Verbose',args.Verbose, ...
    'SourceMinKV',args.SourceMinKV, ...
    'TripMargin',args.TripMargin, 'RandomTrip',args.RandomTrip, ...
    'DeterministicNodes',args.DeterministicNodes, 'NodeFailThresh',args.NodeFailThresh, ...
    'DeterministicEdges',args.DeterministicEdges, 'EdgeFailThresh',args.EdgeFailThresh, ...
    'CapCalibK',args.CapCalibK, 'CapFloorFrac',args.CapFloorFrac, ...
    'DoubleCircuit',args.DoubleCircuit, ...
    'UseStationCouplers',args.UseStationCouplers, ...
    'StationTol',args.StationTol, 'StationCapMult',args.StationCapMult, ...
    'MaxCoupleEachLow',args.MaxCoupleEachLow );
end
