%% ===== 本地函数：面板标签 a/b/c/d（内嵌于坐标轴，稳定随缩放）=====
function placePanelLabel(ax, labelChar, fontName, fs, col)
    text(ax, -0.08, 1.02, labelChar, ...
        'Units','normalized','FontName',fontName,'FontSize',fs, ...
        'FontWeight','bold','Color',col, ...
        'HorizontalAlignment','center','VerticalAlignment','middle', ...
        'Clipping','off');
end