function s = save_step(t, nodeAlive, edgeAlive, meanOver, meanRand, fracOver, lostFrac, servedFrac, changedEdgeIdx)
s = struct('t', t, ...
           'nodeAlive', nodeAlive, ...
           'edgeAlive', edgeAlive, ...
           'meanOverload', meanOver, ...
           'meanRandTrip', meanRand, ...
           'fracOverloaded', fracOver, ...
           'lostLoadFrac', lostFrac, ...
           'servedLoadFrac', servedFrac, ...
           'changedEdgeIdx', changedEdgeIdx(:)', ...
           'note', '');
end