function tagPanel_local(ax, ch)
    % 右上角标签：加粗、靠右
    text(ax, 0.98, 0.96, ch, 'Units','normalized', ...
         'FontWeight','bold', 'FontSize',12, ...
         'HorizontalAlignment','right', ...
         'VerticalAlignment','top');
end